# Generated by Django 4.2.30 on 2026-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignment_rules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
