# Generated by Django 4.2.30 on 2026-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_system', '0002_task_assignment_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignment_rules',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
