# Generated by Django 4.2.30 on 2026-06-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_system', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed')], default='UNASSIGNED', max_length=20),
        ),
    ]
