# Generated by Django 4.2.30 on 2026-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_system', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['department', 'active_tasks_count', 'experience_years'], name='idx_dept_tasks_exp'),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='tms_user_profiles',
        ),
    ]
