# Generated by Django 4.2.30 on 2026-06-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS_system', '0007_userprofile_idx_dept_tasks_exp_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='TMS_system_userprofile',
        ),
    ]
